easy_admin:
    site_name: 'Administration'
    user:
        display_name: false
        display_avatar: false
    entities:
        Post:
            class: App\Entity\Post
            form:
                fields:
                    - title
                    - slug
                    - content
                    - { property: 'created_at', type_options: { widget: 'single_text' } }
                    - { property: 'updated_at', type_options: { widget: 'single_text' } }
                    - published
                    - is_note
                    - dossier
        Dossier:
            class: App\Entity\Dossier
        Page:
            class: App\Entity\Page
        Portfolio:
            class: App\Entity\Portfolio