easy_admin:
    site_name: 'Administration'
    entities:
        Post:
            class: App\Entity\Post
        Dossier:
            class: App\Entity\Dossier
        Page:
            class: App\Entity\Page
        Portfolio:
            class: App\Entity\Portfolio