easy_admin:
    site_name: 'Administration'
    user:
        display_name: false
        display_avatar: false
    entities:
        Post:
            class: App\Entity\Post
            form:
                fields:
                    - title
                    - slug
                    - content
                    - { property: 'created_at', type_options: { widget: 'single_text' } }
                    - { property: 'updated_at', type_options: { widget: 'single_text' } }
                    - published
                    - is_note
                    - dossier
        Dossier:
            class: App\Entity\Dossier
        Page:
            class: App\Entity\Page
        Portfolio:
            class: App\Entity\Portfolio
            form:
                fields:
                    - title
                    - slug
                    - link
                    - { property: 'updated_at', type_options: { widget: 'single_text' } }
                    # - { property: 'image', template: 'image.html.twig' }
                    - { property: 'imageFile', type: 'vich_file' }
            list:
                fields:
                    - id
                    - title
                    - slug
                    - link
                    - { property: 'updated_at', type_options: { widget: 'single_text' } }
                    - { property: 'image', template: 'portfolio/image.html.twig', base_path: '%app.path.portfolio_images%' }
