vich_uploader:
    db_driver: orm

    mappings:
        portfolio_image:
            uri_prefix: '%app.path.portfolio_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.portfolio_images%'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
